repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.19.0
    hooks:
      - id: flake8
  -   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
      language_version: python3.9
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [push]
        l5janguage: system
        entry: poetry run pytest
        pass_filenames: false
        types: [python]
